# Don't post comments on PR yet.
comment: off

# Don't mark any PR as failed if the code coverage drops.
coverage:
  status:
    project:
      default:
        target: 0
    patch:
      default:
        target: 0
