cc_test(
    name = "multiply_tests",
    srcs = ["multiply_tests.cpp"],
    deps = [
        "//source/cpp_native/multiply:multiply",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
